"""empty message

Revision ID: 8946ee948d1e
Revises: 
Create Date: 2023-06-17 18:38:45.669571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8946ee948d1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('french_verbs_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('italian_verbs_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portuguese_verbs_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('romanian_verbs_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spanish_verbs_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_db')
    op.drop_table('spanish_verbs_db')
    op.drop_table('romanian_verbs_db')
    op.drop_table('portuguese_verbs_db')
    op.drop_table('italian_verbs_db')
    op.drop_table('french_verbs_db')
    # ### end Alembic commands ###
